# Generated by Django 3.1.6 on 2022-02-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('ph_no', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'tempdb',
            },
        ),
    ]
