# Generated by Django 3.1.6 on 2022-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panacea_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdb',
            name='ph_no',
            field=models.IntegerField(),
        ),
    ]
