# Generated by Django 3.1.6 on 2022-02-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panacea_app', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pat_id',
            field=models.CharField(default='23lkjfds', max_length=10),
            preserve_default=False,
        ),
    ]
